# Generated by Django 4.2.13 on 2024-06-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stage_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage_management_app.staffs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage_management_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage_management_app.staffs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage_management_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('organization_type', models.CharField(max_length=255)),
                ('organization_size', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('contacts', models.CharField(max_length=255)),
                ('topic', models.TextField()),
                ('additional_comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage_management_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pre-assigned', 'Pre-assigned'), ('finalized', 'Finalized')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage_management_app.internship')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage_management_app.staffs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage_management_app.students')),
            ],
        ),
    ]
