# Generated by Django 4.2.13 on 2024-06-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_management_app', '0002_supervisorpreference_studentpreference_internship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='phone',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.TextField(default='00000000000'),
            preserve_default=False,
        ),
    ]
