# Generated by Django 4.2.13 on 2024-06-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stage_management_app', '0003_staffs_phone_students_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='student',
        ),
        migrations.AddField(
            model_name='internship',
            name='student_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='stage_management_app.students'),
            preserve_default=False,
        ),
    ]
