# Generated by Django 4.2.13 on 2024-06-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_management_app', '0004_remove_internship_student_internship_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpreference',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
