# Generated by Django 4.2.13 on 2024-06-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage_management_app', '0006_remove_attendancereport_attendance_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupervisorPreference',
            new_name='StaffPreference',
        ),
    ]
