# Generated by Django 4.2.13 on 2024-06-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_management_app', '0007_rename_supervisorpreference_staffpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='assignment',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpreference',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='pre-assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentpreference',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
