# Generated by Django 4.2.13 on 2024-06-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage_management_app', '0010_staffs_max_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
    ]
