# Generated by Django 4.2.13 on 2024-06-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stage_management_app', '0013_alter_assignment_id_alter_internship_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stage_management_app.students'),
        ),
    ]
