# Generated by Django 4.2.13 on 2024-06-21 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stage_management_app', '0014_alter_internship_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffpreference',
            name='student',
        ),
        migrations.AddField(
            model_name='staffpreference',
            name='internship',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='stage_management_app.internship'),
            preserve_default=False,
        ),
    ]
