# Generated by Django 4.2.13 on 2024-06-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage_management_app', '0016_rename_internship_staffpreference_internships'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffpreference',
            old_name='internships',
            new_name='internship',
        ),
    ]
