# Generated by Django 4.2.13 on 2024-06-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage_management_app', '0017_rename_internships_staffpreference_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='validated',
        ),
    ]
